---
name: 02 Build with BuildKit Cache

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#NEW: (START) ##########################################################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#NEW: (END) ############################################################
      
      - name: Read current version
        id: read_version
        run: echo "::set-output name=current_version::$(cat version.txt || echo '0.0.0')"

      - name: Increment version
        id: increment_version
        run: echo "::set-output name=next_version::$(echo ${{ steps.read_version.outputs.current_version }} | awk -F. '{$NF+=1; OFS="."; print $0}' || echo '0.0.0')"

      - name: Write new version to file
        run: echo "${{ steps.increment_version.outputs.next_version }}" > version.txt

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/basic-nlp:${{ steps.increment_version.outputs.next_version }}
#NEW: (START) ##########################################################
          cache-from: type=gha
          cache-to: type=gha,mode=max
#NEW: (END) ############################################################