---
name: 02 Build with BuildKit Cache

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#NEW: (START) ##########################################################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#NEW: (END) ############################################################
      
      - name: Read current version
        id: read_version
        run: |
            if [ -f "version.txt" ]; then
              version=$(cat version.txt)
            else
              version='0.0.0'  # Set default version if file doesn't exist
            fi
            echo "Current version: $version"
            echo "current_version=$version" >> $GITHUB_OUTPUT

      - name: Increment version
        id: increment_version
        run: |
          current_version="${{ steps.read_version.outputs.current_version }}"
          echo "Current version: $current_version" 

          if [[ "$current_version" != "0.0.0" && "$current_version" > "0.0.0" ]]; then
            echo "Version is greater than 0.0.0, updating version"
            # Splitting version into major, minor, and patch components
            IFS='.' read -r major minor patch <<< "$current_version"
            ((patch++))
            next_version="$major.$minor.$patch"
          else
            echo "Version is not greater than 0.0.0, returning 0.0.0"
            next_version="0.0.0"
          fi

          echo "Next version: $next_version"

          # Setting the output
          echo "next_version=$next_version" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/basic-nlp:${{ steps.increment_version.outputs.next_version }}
#NEW: (START) ##########################################################
          # cache-from: type=gha
          # cache-to: type=gha,mode=max
#NEW: (END) ############################################################