---
name: 02 Build with BuildKit Cache

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:


      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
#NEW: (START) ##########################################################
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
#NEW: (END) ############################################################
      
      - name: Read current version
        id: read_version
        run: |
            version=$(cat version.txt)
            if [ -z "$version" ]; then
              version='0.0.0'  # Set default version if file is empty
            fi
            echo "Current version: $version"
            echo "::set-output name=current_version::$version" >> $GITHUB_OUTPUT

      - name: Increment version
        id: increment_version
        run: |
            current_version="${{ steps.read_version.outputs.current_version }}" 
            echo "Current version: $current_version" 
            next_version=$(awk -F. '{printf "%d.%d.%d", $1, $2, $3 + 1}' <<< "$current_version" || echo '0.0.0')
            echo "::set-output name=next_version::$next_version" >> $GITHUB_OUTPUT

      - name: Write new version to file
        run: echo "${{ steps.increment_version.outputs.next_version }}" > version.txt

      - name: Debug next_version
        run: echo "${{ steps.increment_version.outputs.next_version }}"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/basic-nlp:${{ steps.increment_version.outputs.next_version }}
#NEW: (START) ##########################################################
          cache-from: type=gha
          cache-to: type=gha,mode=max
#NEW: (END) ############################################################